DiagnosticMethod.create(name: 'Test rápido')
DiagnosticMethod.create(name: 'PCR')
DiagnosticMethod.create(name: 'Contacto epidemiológico')

ContactType.create(name: 'Conviviente')
ContactType.create(name: 'Social')
ContactType.create(name: 'Laboral')

CaseStatus.create(name: 'Sospechoso', badge: 'secondary')
CaseStatus.create(name: 'Pendiente', badge: 'warning')
CaseStatus.create(name: 'Positivo', badge: 'danger')
CaseStatus.create(name: 'Negativo', badge: 'secondary')
CaseStatus.create(name: 'Recuperado', badge: 'success')
CaseStatus.create(name: 'Fallecido', badge: 'dark')
CaseStatus.create(name: 'Bloqueado', badge: 'primary')
