default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: ''

development:
  <<: *default
  database: sifaho_development
  username: sifaho
  password: 12345678

test:
  <<: *default
  database: sifaho_test
  username: sifaho
  password: 12345678

production:
  <<: *default
  database: sifaho_production
  username: sifaho
  password: <%= ENV['SIFAHO_DATABASE_PASSWORD'] %>
