default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 'localhost'

development:
  <<: *default
  database: covid_sma_development
  username: covidsma
  password: 12345678

test:
  <<: *default
  database: covid_sma_test
  username: covidsma
  password: 12345678

production:
  <<: *default
  database: covid_sma_production
  username: covidsma
  password: <%= ENV['COVID_SMA_DATABASE_PASSWORD'] %>
