default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: sifaho_development
  username: sifaho
  password: 12345678

test:
  <<: *default
  database: sifaho_test
  username: sifaho
  password: 12345678

production:
  <<: *default
  database: sifaho_production
  username: sifaho
  password: <%= ENV['SIFAHO_DATABASE_PASSWORD'] %>

db2:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: 10.10.8.21
  database:
  username:
  password: 1
  port: 5432
