# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f71afc18dbb5040a250937093fbc8f5f857b17ca536cee4ec6947425b75c9fc0217cba749ec013da7544020b39ae1199062e1a2f23e5ec7fa942ab718dc80451

test:
  secret_key_base: 2f1f4b87dd8ee42d46e5b3c9761f6d11bb24e053262ce0bb646c2e52e21ca79ca88f266813e94aebef81956fff87f5a69629280c7387b1c5db8d7682985ef9ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1d809f16bf37f164e63e540e029322cc18cea1ef60d5f27e509e5f42a788c35a91570733d975de81e1ea3defad729685a5965316fb76985e445384e278147c71

